### ISSUE TITLE
how to install  panel ?

### ISSUE THREAD

**Issue by w796933** [khaleghsalehi/panel#1]
sir ,how to install  panel ?

**Comment by khaleghsalehi** [comment]
The latest jar file is available [here](https://github.com/khaleghsalehi/ironfox/blob/master/manager/panel.jar). 
 you are welcome to build the panel code too, then copy the jar file to IronFox manager folder [here](https://github.com/khaleghsalehi/ironfox/tree/master/manager)
 in order to run panel manually flow below command for exmaple:
`sudo java -jar /YOURPATH/panel.jar  --spring.config.location=/YOURPATH/application.properties
`
